#4 TO - DO - Task
Please complete all the problem listed below.

4.1 Exercise on Functions:

Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def convert_units(conversion_type, from_unit, to_unit, value):
    """
    Convert a value from one unit to another based on the conversion type.

    Parameters:
    - conversion_type (str): Type of conversion ('length', 'weight', 'volume').
    - from_unit (str): The unit to convert from (e.g., 'm', 'kg', 'L').
    - to_unit (str): The unit to convert to (e.g., 'ft', 'lbs', 'gal').
    - value (float): The numeric value to convert.

    Returns:
    - float: The converted value.

    Raises:
    - ValueError: If an unsupported conversion is requested.
    """
    if conversion_type == "length":
        if from_unit == "m" and to_unit == "ft":
            return value * 3.28084
        elif from_unit == "ft" and to_unit == "m":
            return value / 3.28084
        else:
            raise ValueError("Unsupported length conversion.")
    elif conversion_type == "weight":
        if from_unit == "kg" and to_unit == "lbs":
            return value * 2.20462
        elif from_unit == "lbs" and to_unit == "kg":
            return value / 2.20462
        else:
            raise ValueError("Unsupported weight conversion.")
    elif conversion_type == "volume":
        if from_unit == "L" and to_unit == "gal":
            return value * 0.264172
        elif from_unit == "gal" and to_unit == "L":
            return value / 0.264172
        else:
            raise ValueError("Unsupported volume conversion.")
    else:
        raise ValueError("Unsupported conversion type.")


def main():
    print("Welcome to the Unit Converter!")
    print("Conversion Types: length, weight, volume")

    try:
        conversion_type = input("Enter conversion type: ").strip().lower()
        value = float(input("Enter the value to convert: "))

        if conversion_type == "length":
            from_unit = input("Convert from (m/ft): ").strip().lower()
            to_unit = input("Convert to (m/ft): ").strip().lower()
        elif conversion_type == "weight":
            from_unit = input("Convert from (kg/lbs): ").strip().lower()
            to_unit = input("Convert to (kg/lbs): ").strip().lower()
        elif conversion_type == "volume":
            from_unit = input("Convert from (L/gal): ").strip().lower()
            to_unit = input("Convert to (L/gal): ").strip().lower()
        else:
            print("Invalid conversion type.")
            return

        # Perform conversion
        result = convert_units(conversion_type, from_unit, to_unit, value)
        print(f"{value} {from_unit} = {result:.4f} {to_unit}")

    except ValueError as ve:
        print(f"Error: {ve}")
    except Exception as e:
        print(f"Invalid input: {e}")


if __name__ == "__main__":
    main()

Welcome to the Unit Converter!
Conversion Types: length, weight, volume
Enter conversion type: length
Enter the value to convert: 10
Convert from (m/ft): m
Convert to (m/ft): ft
10.0 m = 32.8084 ft


#Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.


In [ ]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers to sum.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The average value of the numbers.
    """
    return sum(numbers) / len(numbers)

def calculate_max(numbers):
    """
    Find the maximum number in a list.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The maximum number.
    """
    return max(numbers)

def calculate_min(numbers):
    """
    Find the minimum number in a list.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The minimum number.
    """
    return min(numbers)


def main():
    print("Mathematical Operations on a List of Numbers")
    print("Operations: sum, average, max, min")

    try:
        # Get operation
        operation = input("Enter operation: ").strip().lower()

        # Get list of numbers from user
        num_str = input("Enter numbers separated by spaces: ").strip()
        numbers = [float(x) for x in num_str.split()]

        if not numbers:
            raise ValueError("The list of numbers cannot be empty.")

        # Perform the selected operation
        if operation == "sum":
            result = calculate_sum(numbers)
        elif operation == "average":
            result = calculate_average(numbers)
        elif operation == "max":
            result = calculate_max(numbers)
        elif operation == "min":
            result = calculate_min(numbers)
        else:
            print("Invalid operation selected.")
            return

        print(f"Result of {operation} operation: {result}")

    except ValueError as ve:
        print(f"Error: {ve}")
    except Exception as e:
        print(f"Invalid input: {e}")


if __name__ == "__main__":
    main()

Mathematical Operations on a List of Numbers
Operations: sum, average, max, min
Enter operation: sum
Enter numbers separated by spaces: 7 14 21 28
Result of sum operation: 70.0


#4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """
    Extract every other element from a list, starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]  # Slice with step 2 to get every other element


# Example usage
example_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(example_list)
print("Original list:", example_list)
print("Every other element:", result)

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]


#2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    # return sublist from start index to end index (inclusive)
    return lst[start:end+1]


# Example
numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)

print(result)

[3, 4, 5]


3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    # return the reversed list using slicing
    return lst[::-1]

# Example
numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)

print(result)

[5, 4, 3, 2, 1]


##4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    # return list without first and last elements
    return lst[1:-1]

# Example
numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)

print(result)

[2, 3, 4]


#5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    # return first n elements of the list
    return lst[:n]

# Example
numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)

print(result)

[1, 2, 3]


#6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    # return last n elements of the list
    return lst[-n:]

# Example
numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)

print(result)

[4, 5]


#7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    # start from second-to-last element and move backward skipping one element
    return lst[-2::-2]

# Example
numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)

print(result)

[5, 3, 1]


#4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    flat_list = []

    for sublist in lst:
        for item in sublist:
            flat_list.append(item)

    return flat_list


# Example
numbers = [[1, 2], [3, 4], [5]]
result = flatten(numbers)

print(result)

[1, 2, 3, 4, 5]


#2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element


# Example
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

result = access_nested_element(lst, indices)
print(result)

6


#3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    total = 0

    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)   # recursive call for nested list
        else:
            total += item

    return total


# Example
numbers = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(numbers)

print(result)

21


#4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    new_list = []

    for item in lst:
        if isinstance(item, list):
            new_list.append(remove_element(item, elem))  # recursive call
        elif item != elem:
            new_list.append(item)

    return new_list


# Example
lst = [[1, 2], [3, 2], [4, 5]]
result = remove_element(lst, 2)

print(result)

[[1], [3], [4, 5]]


#5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    max_val = float('-inf')  # start with smallest possible number

    for item in lst:
        if isinstance(item, list):
            # recursively find max in sublist
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)

    return max_val


# Example
numbers = [[1, 2], [3, [4, 5]], 6]
result = find_max(numbers)

print(result)

6


#6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # recursive call
        elif item == elem:
            count += 1
    return count


# Example
lst = [[1, 2], [2, 3], [2, 4]]
result = count_occurrences(lst, 2)

print(result)

3


#7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    flat_list = []

    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # recursive call
        else:
            flat_list.append(item)

    return flat_list


# Example
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)

print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


#8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    def helper(sublist):
        total = 0
        count = 0
        for item in sublist:
            if isinstance(item, list):
                t, c = helper(item)  # recursive call
                total += t
                count += c
            else:
                total += item
                count += 1
        return total, count

    total_sum, total_count = helper(lst)
    if total_count == 0:
        return 0  # avoid division by zero
    return total_sum / total_count


# Example
nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)

print(result)

3.5


#10 To - Do - NumPy
Please complete all the problems listed below:

#10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.


In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty 2x2 array:\n", empty_array)

Empty 2x2 array:
 [[3.00881727e-315 0.00000000e+000]
 [4.94065646e-324             nan]]


#2. Initialize an all one array with size 4X2.

In [ ]:
# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll-one 4x2 array:\n", ones_array)


All-one 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:

# 3. Return a new array of given shape and type, filled with a fill value
# Example: shape = (3,3), fill value = 7, dtype = int
filled_array = np.full((3, 3), 7, dtype=int)
print("\nFilled array 3x3 with 7:\n", filled_array)



Filled array 3x3 with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[5, 6], [7, 8]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros array like given array:\n", zeros_like_array)


Zeros array like given array:
 [[0 0]
 [0 0]]


#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\nOnes array like given array:\n", ones_like_array)



Ones array like given array:
 [[1 1]
 [1 1]]


#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nArray from list [1,2,3,4]:\n", array_from_list)


Array from list [1,2,3,4]:
 [1 2 3 4]


#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.


In [ ]:
import numpy as np

# Task 1: array from 10 to 49
array_10_49 = np.arange(10, 50)  # end is exclusive
print("Array from 10 to 49:\n", array_10_49)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
# Task 2: 3x3 matrix
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print("3x3 matrix with values 0 to 8:\n", matrix_3x3)

3x3 matrix with values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


#3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
# Task 3: identity matrix
identity_matrix = np.eye(3)
print("3x3 identity matrix:\n", identity_matrix)

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
# Task 4: random array and mean
random_array_30 = np.random.random(30)  # random floats [0,1)
mean_value = random_array_30.mean()
print("Random array of size 30:\n", random_array_30)
print("Mean of the array:", mean_value)

Random array of size 30:
 [0.23893822 0.23932539 0.95726848 0.83725537 0.82881297 0.59104538
 0.89778334 0.3903242  0.81301655 0.96563928 0.28247248 0.94200561
 0.89170467 0.44016535 0.07965892 0.07516086 0.47318868 0.3603615
 0.52397034 0.64329614 0.28634783 0.2695517  0.55341849 0.51988758
 0.81888694 0.16009632 0.58498195 0.16440066 0.16211977 0.82209889]
Mean of the array: 0.5271061287267221


#5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
# Task 5: 10x10 random array
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("10x10 random array:\n", random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

10x10 random array:
 [[0.77407664 0.58312989 0.97366234 0.28468669 0.28793992 0.46197563
  0.47346394 0.99778323 0.55901568 0.93991727]
 [0.7971628  0.43090953 0.28719022 0.61364283 0.75011592 0.45637658
  0.16336516 0.13851188 0.61556461 0.6303468 ]
 [0.36601617 0.50622775 0.80783798 0.59008992 0.80067068 0.18812432
  0.88880177 0.10493736 0.54170747 0.03240809]
 [0.11189895 0.78134485 0.66080797 0.54882231 0.95997664 0.67517756
  0.22927178 0.53232455 0.37906099 0.48021692]
 [0.05419143 0.95594145 0.46609384 0.97900963 0.75024593 0.18581984
  0.81033088 0.26787016 0.68060801 0.08108235]
 [0.76692963 0.62660507 0.43491753 0.08747345 0.54991797 0.36531611
  0.40217307 0.1124322  0.39567875 0.31675818]
 [0.24874776 0.78562104 0.42291427 0.55839297 0.85838038 0.68302296
  0.55319077 0.28230178 0.05151272 0.53029587]
 [0.83360453 0.62958125 0.72731444 0.30182735 0.58934589 0.53638895
  0.08550137 0.8359275  0.92292726 0.83738253]
 [0.49407821 0.23144865 0.52403587 0.43421571 0.31873318 0.

#6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
# Task 6: zero array and replace 5th element
zero_array_10 = np.zeros(10)
zero_array_10[4] = 1  # index starts from 0
print("Zero array with 5th element as 1:\n", zero_array_10)

Zero array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed array:\n", reversed_arr)

Reversed array:
 [0 4 0 0 2 1]


#8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
# Task 8: 2D array with border 1s
n, m = 5, 5  # example size
border_array = np.ones((n, m))
border_array[1:-1, 1:-1] = 0
print("2D array with 1 on border and 0 inside:\n", border_array)

2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
# Task 9: checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # fill alternating rows starting from row 1
checkerboard[::2, 1::2] = 1  # fill alternating rows starting from row 0
print("8x8 checkerboard pattern:\n", checkerboard)

8x8 checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [ ]:
# Task 1: addition
add_xy = x + y
print("x + y =\n", add_xy)

x + y =
 [[ 6  8]
 [10 13]]


#2. Subtract the two array.

In [ ]:
# Task 2: subtraction
sub_xy = x - y
print("x - y =\n", sub_xy)

x - y =
 [[-4 -4]
 [-4 -3]]


#3. Multiply the array with any integers of your choice.

In [ ]:
# Task 3: multiply x by 3
mul_x = x * 3
print("x * 3 =\n", mul_x)

x * 3 =
 [[ 3  6]
 [ 9 15]]


#4. Find the square of each element of the array.

In [ ]:
# Task 4: square of elements
square_x = x ** 2
print("Square of x =\n", square_x)

Square of x =
 [[ 1  4]
 [ 9 25]]


#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Dot products
dot_vw = np.dot(v, w)       # v . w
dot_xv = np.dot(x, v)       # x . v
dot_xy = np.dot(x, y)       # x . y

print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


#6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1️⃣ Concatenate x and y along rows (axis=0)
concat_xy_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows:\n", concat_xy_row)

# 2️⃣ Concatenate v and w along columns
# First, convert v and w to column vectors if needed
concat_vw_col = np.column_stack((v, w))
print("\nConcatenate v and w along columns:\n", concat_vw_col)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("Error:", e)
concat_xv_fixed = np.concatenate((x, v.reshape(1,2)), axis=0)
print("Concatenate x and v after reshaping v:\n", concat_xv_fixed)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Concatenate x and v after reshaping v:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

#Prove A.A−1 = I.

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# Compute inverse of A
A_inv = np.linalg.inv(A)

# Multiply A with its inverse
result = np.dot(A, A_inv)
print("A * A_inv =\n", result)

# Identity matrix for comparison
I = np.eye(2)
print("Identity matrix:\n", I)

A * A_inv =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity matrix:
 [[1. 0.]
 [0. 1.]]


# Prove AB ̸= BA.

In [ ]:
# Multiply AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("A * B =\n", AB)
print("B * A =\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

A * B =
 [[23 13]
 [51 29]]
B * A =
 [[36 44]
 [13 16]]
Are AB and BA equal? False


# Prove (AB)T = BTAT


In [ ]:
# Transpose of AB
AB_T = (np.dot(A, B)).T

# Bᵀ * Aᵀ
B_T_A_T = np.dot(B.T, A.T)

print("(AB).T =\n", AB_T)
print("B.T * A.T =\n", B_T_A_T)
print("Are they equal?", np.array_equal(AB_T, B_T_A_T))

(AB).T =
 [[23 51]
 [13 29]]
B.T * A.T =
 [[23 51]
 [13 29]]
Are they equal? True


# Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func- tion of Numpy}

In [ ]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

# Constant vector B
B = np.array([-1, -3, 9])

# Solve using inverse: X = A^-1 * B
X = np.dot(np.linalg.inv(A), B)

print("Solution [x, y, z] using inverse method:", X)

Solution [x, y, z] using inverse method: [ 2.  1. -2.]


#